__dependents_rules__(
    (
        # only files within this tests directory can import from its contents.
        "*",
        (
            # Allow
            "/*",
            "/**"
        ),
        (
            # Deny
            "!*",
        )
    )
)

python_sources()
